export const s3Url = 'https://gigremotely.s3-ap-southeast-1.amazonaws.com/';
export const listContractType = [
  { value: 'FREELANCE', name: 'Freelance', background: '#4ad3b9' },
  { value: 'PART_TIME', name: 'Part Time', background: '#a5a75a' },
  { value: 'FULL_TIME', name: 'Full Time', background: '#fa7d00' },
];
export const listDuration = [
  { value: '1-2 months', name: '1-2 mths' },
  { value: '3-5 months', name: '3-5 mths' },
  { value: '6-9 months', name: '6-9 mths' },
  { value: '10-12 months', name: '10-12 mths' },
  { value: '> 12 months', name: '> 12 mths' },
];
export const listRoleLevel = [
  { value: 'Intern', name: 'Intern' },
  { value: 'Junior', name: 'Junior' },
  { value: 'Senior', name: 'Senior' },
];
export const jobCategory = [
  { value: 'Branding', name: 'Branding' },
  { value: 'Marketing', name: 'Marketing' },
  { value: 'Development', name: 'Development' },
  { value: 'Digital Marketing', name: 'Digital Marketing' },
  { value: 'Illustration', name: 'Illustration' },
  { value: 'UXUI Design', name: 'UXUI Design' },
  { value: 'Copywriting', name: 'Copywriting' },
  { value: 'Consultants', name: 'Consultants' },
  { value: 'Content Management', name: 'Content Management' },
  { value: 'Others', name: 'Others' },
];
export const listTimezone = [
  { name: '(GMT -12:00) Eniwetok, Kwajalein', value: '-12:00' },
  { name: '(GMT -11:00) Midway Island, Samoa', value: '-11:00' },
  { name: '(GMT -10:00) Hawaii', value: '-10:00' },
  { name: '(GMT -9:30) Taiohae', value: '-09:50' },
  { name: '(GMT -9:00) Alaska', value: '-09:00' },
  { name: '(GMT -8:00) Pacific Time (US &amp; Canada)', value: '-08:00' },
  { name: '(GMT -7:00) Mountain Time (US &amp; Canada)', value: '-07:00' },
  { name: '(GMT -6:00) Central Time (US &amp; Canada), Mexico City', value: '-06:00' },
  { name: '(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima', value: '-05:00' },
  { name: '(GMT -4:30) Caracas', value: '-04:50' },
  { name: '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz', value: '-04:00' },
  { name: '(GMT -3:30) Newfoundland', value: '-03:50' },
  { name: '(GMT -3:00) Brazil, Buenos Aires, Georgetown', value: '-03:00' },
  { name: '(GMT -2:00) Mid-Atlantic', value: '-02:00' },
  { name: '(GMT -1:00) Azores, Cape Verde Islands', value: '-01:00' },
  { name: '(GMT) Western Europe Time, London, Lisbon, Casablanca', value: '+00:00' },
  { name: '(GMT +1:00) Brussels, Copenhagen, Madrid, Paris', value: '+01:00' },
  { name: '(GMT +2:00) Kaliningrad, South Africa', value: '+02:00' },
  { name: '(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg', value: '+03:00' },
  { name: '(GMT +3:30) Tehran', value: '+03:50' },
  { name: '(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi', value: '+04:00' },
  { name: '(GMT +4:30) Kabul', value: '+04:50' },
  { name: '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent', value: '+05:00' },
  { name: '(GMT +5:30) Bombay, Calcutta, Madras, New Delhi', value: '+05:50' },
  { name: '(GMT +5:45) Kathmandu, Pokhara', value: '+05:75' },
  { name: '(GMT +6:00) Almaty, Dhaka, Colombo', value: '+06:00' },
  { name: '(GMT +6:30) Yangon, Mandalay', value: '+06:50' },
  { name: '(GMT +7:00) Bangkok, Hanoi, Jakarta', value: '+07:00' },
  { name: '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong', value: '+08:00' },
  { name: '(GMT +8:45) Eucla', value: '+08:75' },
  { name: '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk', value: '+09:00' },
  { name: '(GMT +9:30) Adelaide, Darwin', value: '+09:50' },
  { name: '(GMT +10:00) Eastern Australia, Guam, Vladivostok', value: '+10:00' },
  { name: '(GMT +10:30) Lord Howe Island', value: '+10:50' },
  { name: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia', value: '+11:00' },
  { name: '(GMT +11:30) Norfolk Island', value: '+11:50' },
  { name: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka', value: '+12:00' },
  { name: '(GMT +12:45) Chatham Islands', value: '+12:75' },
  { name: '(GMT +13:00) Apia, Nukualofa', value: '+13:00' },
  { name: '(GMT +14:00) Line Islands, Tokelau', value: '+14:00' },
];
export const country = [
  { value: 'Afghanistan', name: 'Afghanistan' },
  { value: 'Albania', name: 'Albania' },
  { value: 'Algeria', name: 'Algeria' },
  { value: 'American Samoa', name: 'American Samoa' },
  { value: 'Andorra', name: 'Andorra' },
  { value: 'Angola', name: 'Angola' },
  { value: 'Anguilla', name: 'Anguilla' },
  { value: 'Antarctica', name: 'Antarctica' },
  { value: 'Antigua and Barbuda', name: 'Antigua and Barbuda' },
  { value: 'Argentina', name: 'Argentina' },
  { value: 'Armenia', name: 'Armenia' },
  { value: 'Aruba', name: 'Aruba' },
  { value: 'Australia', name: 'Australia' },
  { value: 'Austria', name: 'Austria' },
  { value: 'Azerbaijan', name: 'Azerbaijan' },
  { value: 'Bahamas (the)', name: 'Bahamas (the)' },
  { value: 'Bahrain', name: 'Bahrain' },
  { value: 'Bangladesh', name: 'Bangladesh' },
  { value: 'Barbados', name: 'Barbados' },
  { value: 'Belarus', name: 'Belarus' },
  { value: 'Belgium', name: 'Belgium' },
  { value: 'Belize', name: 'Belize' },
  { value: 'Benin', name: 'Benin' },
  { value: 'Bermuda', name: 'Bermuda' },
  { value: 'Bhutan', name: 'Bhutan' },
  { value: 'Bolivia (Plurinational State of)', name: 'Bolivia (Plurinational State of)' },
  { value: 'Bonaire, Sint Eustatius and Saba', name: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'Bosnia and Herzegovina', name: 'Bosnia and Herzegovina' },
  { value: 'Botswana', name: 'Botswana' },
  { value: 'Bouvet Island', name: 'Bouvet Island' },
  { value: 'Brazil', name: 'Brazil' },
  { value: 'British Indian Ocean Territory (the)', name: 'British Indian Ocean Territory (the)' },
  { value: 'Brunei Darussalam', name: 'Brunei Darussalam' },
  { value: 'Bulgaria', name: 'Bulgaria' },
  { value: 'Burkina Faso', name: 'Burkina Faso' },
  { value: 'Burundi', name: 'Burundi' },
  { value: 'Cabo Verde', name: 'Cabo Verde' },
  { value: 'Cambodia', name: 'Cambodia' },
  { value: 'Cameroon', name: 'Cameroon' },
  { value: 'Canada', name: 'Canada' },
  { value: 'Cayman Islands (the)', name: 'Cayman Islands (the)' },
  { value: 'Central African Republic (the)', name: 'Central African Republic (the)' },
  { value: 'Chad', name: 'Chad' },
  { value: 'Chile', name: 'Chile' },
  { value: 'China', name: 'China' },
  { value: 'Christmas Island', name: 'Christmas Island' },
  { value: 'Cocos (Keeling) Islands (the)', name: 'Cocos (Keeling) Islands (the)' },
  { value: 'Colombia', name: 'Colombia' },
  { value: 'Comoros (the)', name: 'Comoros (the)' },
  { value: 'Congo (the Democratic Republic of the)', name: 'Congo (the Democratic Republic of the)' },
  { value: 'Congo (the)', name: 'Congo (the)' },
  { value: 'Cook Islands (the)', name: 'Cook Islands (the)' },
  { value: 'Costa Rica', name: 'Costa Rica' },
  { value: 'Croatia', name: 'Croatia' },
  { value: 'Cuba', name: 'Cuba' },
  { value: 'Curaçao', name: 'Curaçao' },
  { value: 'Cyprus', name: 'Cyprus' },
  { value: 'Czechia', name: 'Czechia' },
  { value: "Côte d'Ivoire", name: "Côte d'Ivoire" },
  { value: 'Denmark', name: 'Denmark' },
  { value: 'Djibouti', name: 'Djibouti' },
  { value: 'Dominica', name: 'Dominica' },
  { value: 'Dominican Republic (the)', name: 'Dominican Republic (the)' },
  { value: 'Ecuador', name: 'Ecuador' },
  { value: 'Egypt', name: 'Egypt' },
  { value: 'El Salvador', name: 'El Salvador' },
  { value: 'Equatorial Guinea', name: 'Equatorial Guinea' },
  { value: 'Eritrea', name: 'Eritrea' },
  { value: 'Estonia', name: 'Estonia' },
  { value: 'Eswatini', name: 'Eswatini' },
  { value: 'Ethiopia', name: 'Ethiopia' },
  { value: 'Falkland Islands (the) [Malvinas]', name: 'Falkland Islands (the) [Malvinas]' },
  { value: 'Faroe Islands (the)', name: 'Faroe Islands (the)' },
  { value: 'Fiji', name: 'Fiji' },
  { value: 'Finland', name: 'Finland' },
  { value: 'France', name: 'France' },
  { value: 'French Guiana', name: 'French Guiana' },
  { value: 'French Polynesia', name: 'French Polynesia' },
  { value: 'French Southern Territories (the)', name: 'French Southern Territories (the)' },
  { value: 'Gabon', name: 'Gabon' },
  { value: 'Gambia (the)', name: 'Gambia (the)' },
  { value: 'Georgia', name: 'Georgia' },
  { value: 'Germany', name: 'Germany' },
  { value: 'Ghana', name: 'Ghana' },
  { value: 'Gibraltar', name: 'Gibraltar' },
  { value: 'Greece', name: 'Greece' },
  { value: 'Greenland', name: 'Greenland' },
  { value: 'Grenada', name: 'Grenada' },
  { value: 'Guadeloupe', name: 'Guadeloupe' },
  { value: 'Guam', name: 'Guam' },
  { value: 'Guatemala', name: 'Guatemala' },
  { value: 'Guernsey', name: 'Guernsey' },
  { value: 'Guinea', name: 'Guinea' },
  { value: 'Guinea-Bissau', name: 'Guinea-Bissau' },
  { value: 'Guyana', name: 'Guyana' },
  { value: 'Haiti', name: 'Haiti' },
  { value: 'Heard Island and McDonald Islands', name: 'Heard Island and McDonald Islands' },
  { value: 'Holy See (the)', name: 'Holy See (the)' },
  { value: 'Honduras', name: 'Honduras' },
  { value: 'Hong Kong', name: 'Hong Kong' },
  { value: 'Hungary', name: 'Hungary' },
  { value: 'Iceland', name: 'Iceland' },
  { value: 'India', name: 'India' },
  { value: 'Indonesia', name: 'Indonesia' },
  { value: 'Iran (Islamic Republic of)', name: 'Iran (Islamic Republic of)' },
  { value: 'Iraq', name: 'Iraq' },
  { value: 'Ireland', name: 'Ireland' },
  { value: 'Isle of Man', name: 'Isle of Man' },
  { value: 'Israel', name: 'Israel' },
  { value: 'Italy', name: 'Italy' },
  { value: 'Jamaica', name: 'Jamaica' },
  { value: 'Japan', name: 'Japan' },
  { value: 'Jersey', name: 'Jersey' },
  { value: 'Jordan', name: 'Jordan' },
  { value: 'Kazakhstan', name: 'Kazakhstan' },
  { value: 'Kenya', name: 'Kenya' },
  { value: 'Kiribati', name: 'Kiribati' },
  { value: "Korea (the Democratic People's Republic of)", name: "Korea (the Democratic People's Republic of)" },
  { value: 'Korea (the Republic of)', name: 'Korea (the Republic of)' },
  { value: 'Kuwait', name: 'Kuwait' },
  { value: 'Kyrgyzstan', name: 'Kyrgyzstan' },
  { value: "Lao People's Democratic Republic (the)", name: "Lao People's Democratic Republic (the)" },
  { value: 'Latvia', name: 'Latvia' },
  { value: 'Lebanon', name: 'Lebanon' },
  { value: 'Lesotho', name: 'Lesotho' },
  { value: 'Liberia', name: 'Liberia' },
  { value: 'Libya', name: 'Libya' },
  { value: 'Liechtenstein', name: 'Liechtenstein' },
  { value: 'Lithuania', name: 'Lithuania' },
  { value: 'Luxembourg', name: 'Luxembourg' },
  { value: 'Macao', name: 'Macao' },
  { value: 'Madagascar', name: 'Madagascar' },
  { value: 'Malawi', name: 'Malawi' },
  { value: 'Malaysia', name: 'Malaysia' },
  { value: 'Maldives', name: 'Maldives' },
  { value: 'Mali', name: 'Mali' },
  { value: 'Malta', name: 'Malta' },
  { value: 'Marshall Islands (the)', name: 'Marshall Islands (the)' },
  { value: 'Martinique', name: 'Martinique' },
  { value: 'Mauritania', name: 'Mauritania' },
  { value: 'Mauritius', name: 'Mauritius' },
  { value: 'Mayotte', name: 'Mayotte' },
  { value: 'Mexico', name: 'Mexico' },
  { value: 'Micronesia (Federated States of)', name: 'Micronesia (Federated States of)' },
  { value: 'Moldova (the Republic of)', name: 'Moldova (the Republic of)' },
  { value: 'Monaco', name: 'Monaco' },
  { value: 'Mongolia', name: 'Mongolia' },
  { value: 'Montenegro', name: 'Montenegro' },
  { value: 'Montserrat', name: 'Montserrat' },
  { value: 'Morocco', name: 'Morocco' },
  { value: 'Mozambique', name: 'Mozambique' },
  { value: 'Myanmar', name: 'Myanmar' },
  { value: 'Namibia', name: 'Namibia' },
  { value: 'Nauru', name: 'Nauru' },
  { value: 'Nepal', name: 'Nepal' },
  { value: 'Netherlands (the)', name: 'Netherlands (the)' },
  { value: 'New Caledonia', name: 'New Caledonia' },
  { value: 'New Zealand', name: 'New Zealand' },
  { value: 'Nicaragua', name: 'Nicaragua' },
  { value: 'Niger (the)', name: 'Niger (the)' },
  { value: 'Nigeria', name: 'Nigeria' },
  { value: 'Niue', name: 'Niue' },
  { value: 'Norfolk Island', name: 'Norfolk Island' },
  { value: 'Northern Mariana Islands (the)', name: 'Northern Mariana Islands (the)' },
  { value: 'Norway', name: 'Norway' },
  { value: 'Oman', name: 'Oman' },
  { value: 'Pakistan', name: 'Pakistan' },
  { value: 'Palau', name: 'Palau' },
  { value: 'Palestine, State of', name: 'Palestine, State of' },
  { value: 'Panama', name: 'Panama' },
  { value: 'Papua New Guinea', name: 'Papua New Guinea' },
  { value: 'Paraguay', name: 'Paraguay' },
  { value: 'Peru', name: 'Peru' },
  { value: 'Philippines (the)', name: 'Philippines (the)' },
  { value: 'Pitcairn', name: 'Pitcairn' },
  { value: 'Poland', name: 'Poland' },
  { value: 'Portugal', name: 'Portugal' },
  { value: 'Puerto Rico', name: 'Puerto Rico' },
  { value: 'Qatar', name: 'Qatar' },
  { value: 'Republic of North Macedonia', name: 'Republic of North Macedonia' },
  { value: 'Romania', name: 'Romania' },
  { value: 'Russian Federation (the)', name: 'Russian Federation (the)' },
  { value: 'Rwanda', name: 'Rwanda' },
  { value: 'Réunion', name: 'Réunion' },
  { value: 'Saint Barthélemy', name: 'Saint Barthélemy' },
  { value: 'Saint Helena, Ascension and Tristan da Cunha', name: 'Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'Saint Kitts and Nevis', name: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', name: 'Saint Lucia' },
  { value: 'Saint Martin (French part)', name: 'Saint Martin (French part)' },
  { value: 'Saint Pierre and Miquelon', name: 'Saint Pierre and Miquelon' },
  { value: 'Saint Vincent and the Grenadines', name: 'Saint Vincent and the Grenadines' },
  { value: 'Samoa', name: 'Samoa' },
  { value: 'San Marino', name: 'San Marino' },
  { value: 'Sao Tome and Principe', name: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', name: 'Saudi Arabia' },
  { value: 'Senegal', name: 'Senegal' },
  { value: 'Serbia', name: 'Serbia' },
  { value: 'Seychelles', name: 'Seychelles' },
  { value: 'Sierra Leone', name: 'Sierra Leone' },
  { value: 'Singapore', name: 'Singapore' },
  { value: 'Sint Maarten (Dutch part)', name: 'Sint Maarten (Dutch part)' },
  { value: 'Slovakia', name: 'Slovakia' },
  { value: 'Slovenia', name: 'Slovenia' },
  { value: 'Solomon Islands', name: 'Solomon Islands' },
  { value: 'Somalia', name: 'Somalia' },
  { value: 'South Africa', name: 'South Africa' },
  { value: 'South Georgia and the South Sandwich Islands', name: 'South Georgia and the South Sandwich Islands' },
  { value: 'South Sudan', name: 'South Sudan' },
  { value: 'Spain', name: 'Spain' },
  { value: 'Sri Lanka', name: 'Sri Lanka' },
  { value: 'Sudan (the)', name: 'Sudan (the)' },
  { value: 'Suriname', name: 'Suriname' },
  { value: 'Svalbard and Jan Mayen', name: 'Svalbard and Jan Mayen' },
  { value: 'Sweden', name: 'Sweden' },
  { value: 'Switzerland', name: 'Switzerland' },
  { value: 'Syrian Arab Republic', name: 'Syrian Arab Republic' },
  { value: 'Taiwan', name: 'Taiwan' },
  { value: 'Tajikistan', name: 'Tajikistan' },
  { value: 'Tanzania, United Republic of', name: 'Tanzania, United Republic of' },
  { value: 'Thailand', name: 'Thailand' },
  { value: 'Timor-Leste', name: 'Timor-Leste' },
  { value: 'Togo', name: 'Togo' },
  { value: 'Tokelau', name: 'Tokelau' },
  { value: 'Tonga', name: 'Tonga' },
  { value: 'Trinidad and Tobago', name: 'Trinidad and Tobago' },
  { value: 'Tunisia', name: 'Tunisia' },
  { value: 'Turkey', name: 'Turkey' },
  { value: 'Turkmenistan', name: 'Turkmenistan' },
  { value: 'Turks and Caicos Islands (the)', name: 'Turks and Caicos Islands (the)' },
  { value: 'Tuvalu', name: 'Tuvalu' },
  { value: 'Uganda', name: 'Uganda' },
  { value: 'Ukraine', name: 'Ukraine' },
  { value: 'United Arab Emirates (the)', name: 'United Arab Emirates (the)' },
  { value: 'United Kingdom of Great Britain and Northern Ireland (the)', name: 'United Kingdom of Great Britain and Northern Ireland (the)' },
  { value: 'United States Minor Outlying Islands (the)', name: 'United States Minor Outlying Islands (the)' },
  { value: 'United States of America (the)', name: 'United States of America (the)' },
  { value: 'Uruguay', name: 'Uruguay' },
  { value: 'Uzbekistan', name: 'Uzbekistan' },
  { value: 'Vanuatu', name: 'Vanuatu' },
  { value: 'Venezuela (Bolivarian Republic of)', name: 'Venezuela (Bolivarian Republic of)' },
  { value: 'Viet Nam', name: 'Viet Nam' },
  { value: 'Virgin Islands (British)', name: 'Virgin Islands (British)' },
  { value: 'Virgin Islands (U.S.)', name: 'Virgin Islands (U.S.)' },
  { value: 'Wallis and Futuna', name: 'Wallis and Futuna' },
  { value: 'Western Sahara', name: 'Western Sahara' },
  { value: 'Yemen', name: 'Yemen' },
  { value: 'Zambia', name: 'Zambia' },
  { value: 'Zimbabwe', name: 'Zimbabwe' },
  { value: 'Åland Islands', name: 'Åland Islands' },
];
